version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck  # includes gosimple
    - unused
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - gosec
    - prealloc
    - copyloopvar
    - whitespace
    - revive
  settings:
    misspell:
      locale: US
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
    gosec:
      excludes:
        - G101
        - G104
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - noctx
      - path: _test\.go
        text: "exported: exported"
      # Example code doesn't need strict security checks
      - path: examples/
        linters:
          - gosec
          - errcheck
          - noctx
      - path: examples/
        text: "context-keys-type"
      - path: examples/
        text: "package-comments"
      - path: examples/
        text: "SA1019"  # deprecated

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/aloks98/goauth

output:
  sort-order:
    - file
